//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Win32.TaskScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Win32.TaskScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call a COM object.
        /// </summary>
        internal static string ActionTypeComHandler {
            get {
                return ResourceManager.GetString("ActionTypeComHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start a program.
        /// </summary>
        internal static string ActionTypeExecute {
            get {
                return ResourceManager.GetString("ActionTypeExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send an e-mail.
        /// </summary>
        internal static string ActionTypeSendEmail {
            get {
                return ResourceManager.GetString("ActionTypeSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display a message.
        /// </summary>
        internal static string ActionTypeShowMessage {
            get {
                return ResourceManager.GetString("ActionTypeShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {3} {0:P}.
        /// </summary>
        internal static string ComHandlerAction {
            get {
                return ResourceManager.GetString("ComHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à every day.
        /// </summary>
        internal static string DOWAllDays {
            get {
                return ResourceManager.GetString("DOWAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {1} {0}.
        /// </summary>
        internal static string EmailAction {
            get {
                return ResourceManager.GetString("EmailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ..
        /// </summary>
        internal static string EndSentence {
            get {
                return ResourceManager.GetString("EndSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        internal static string ExecAction {
            get {
                return ResourceManager.GetString("ExecAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -.
        /// </summary>
        internal static string HyphenSeparator {
            get {
                return ResourceManager.GetString("HyphenSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ,.
        /// </summary>
        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à every month.
        /// </summary>
        internal static string MOYAllMonths {
            get {
                return ResourceManager.GetString("MOYAllMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiple actions defined.
        /// </summary>
        internal static string MultipleActions {
            get {
                return ResourceManager.GetString("MultipleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiple triggers defined.
        /// </summary>
        internal static string MultipleTriggers {
            get {
                return ResourceManager.GetString("MultipleTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        internal static string ShowMessageAction {
            get {
                return ResourceManager.GetString("ShowMessageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string TaskDefaultPrincipal {
            get {
                return ResourceManager.GetString("TaskDefaultPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        internal static string TaskStateDisabled {
            get {
                return ResourceManager.GetString("TaskStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queued.
        /// </summary>
        internal static string TaskStateQueued {
            get {
                return ResourceManager.GetString("TaskStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        internal static string TaskStateReady {
            get {
                return ResourceManager.GetString("TaskStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        internal static string TaskStateRunning {
            get {
                return ResourceManager.GetString("TaskStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string TaskStateUnknown {
            get {
                return ResourceManager.GetString("TaskStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any user.
        /// </summary>
        internal static string TriggerAnyUser {
            get {
                return ResourceManager.GetString("TriggerAnyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At system startup.
        /// </summary>
        internal static string TriggerBoot1 {
            get {
                return ResourceManager.GetString("TriggerBoot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Trigger.
        /// </summary>
        internal static string TriggerCustom1 {
            get {
                return ResourceManager.GetString("TriggerCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} every day.
        /// </summary>
        internal static string TriggerDaily1 {
            get {
                return ResourceManager.GetString("TriggerDaily1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} every {1} days.
        /// </summary>
        internal static string TriggerDaily2 {
            get {
                return ResourceManager.GetString("TriggerDaily2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à indefinitely.
        /// </summary>
        internal static string TriggerDuration0 {
            get {
                return ResourceManager.GetString("TriggerDuration0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à for a duration of {0}.
        /// </summary>
        internal static string TriggerDurationNot0 {
            get {
                return ResourceManager.GetString("TriggerDurationNot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trigger expires at {0:G}..
        /// </summary>
        internal static string TriggerEndBoundary {
            get {
                return ResourceManager.GetString("TriggerEndBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom event filter.
        /// </summary>
        internal static string TriggerEvent1 {
            get {
                return ResourceManager.GetString("TriggerEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On event - Log: {0}.
        /// </summary>
        internal static string TriggerEventBasic1 {
            get {
                return ResourceManager.GetString("TriggerEventBasic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , Source: {0}.
        /// </summary>
        internal static string TriggerEventBasic2 {
            get {
                return ResourceManager.GetString("TriggerEventBasic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , EventID: {0}.
        /// </summary>
        internal static string TriggerEventBasic3 {
            get {
                return ResourceManager.GetString("TriggerEventBasic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When computer is idle.
        /// </summary>
        internal static string TriggerIdle1 {
            get {
                return ResourceManager.GetString("TriggerIdle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At log on of {0}.
        /// </summary>
        internal static string TriggerLogon1 {
            get {
                return ResourceManager.GetString("TriggerLogon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} on day {1} of {2}, starting {0:d}.
        /// </summary>
        internal static string TriggerMonthly1 {
            get {
                return ResourceManager.GetString("TriggerMonthly1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} on the {1} {2:f} each {3}, starting {0:d}.
        /// </summary>
        internal static string TriggerMonthlyDOW1 {
            get {
                return ResourceManager.GetString("TriggerMonthlyDOW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When the task is created or modified.
        /// </summary>
        internal static string TriggerRegistration1 {
            get {
                return ResourceManager.GetString("TriggerRegistration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After triggered, repeat every {0} {1}..
        /// </summary>
        internal static string TriggerRepetition {
            get {
                return ResourceManager.GetString("TriggerRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On local connection to {0}..
        /// </summary>
        internal static string TriggerSessionConsoleConnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On local disconnect from {0}..
        /// </summary>
        internal static string TriggerSessionConsoleDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On remote connection to {0}..
        /// </summary>
        internal static string TriggerSessionRemoteConnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On remote disconnect from {0}..
        /// </summary>
        internal static string TriggerSessionRemoteDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On workstation lock of {0}..
        /// </summary>
        internal static string TriggerSessionSessionLock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On workstation unlock of {0}..
        /// </summary>
        internal static string TriggerSessionSessionUnlock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à user session of {0}.
        /// </summary>
        internal static string TriggerSessionUserSession {
            get {
                return ResourceManager.GetString("TriggerSessionUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} on {0:d}.
        /// </summary>
        internal static string TriggerTime1 {
            get {
                return ResourceManager.GetString("TriggerTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At startup.
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Trigger.
        /// </summary>
        internal static string TriggerTypeCustom {
            get {
                return ResourceManager.GetString("TriggerTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily.
        /// </summary>
        internal static string TriggerTypeDaily {
            get {
                return ResourceManager.GetString("TriggerTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On an event.
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On idle.
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At log on.
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly.
        /// </summary>
        internal static string TriggerTypeMonthly {
            get {
                return ResourceManager.GetString("TriggerTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly.
        /// </summary>
        internal static string TriggerTypeMonthlyDOW {
            get {
                return ResourceManager.GetString("TriggerTypeMonthlyDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At task creation/modification.
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On state change.
        /// </summary>
        internal static string TriggerTypeSessionStateChange {
            get {
                return ResourceManager.GetString("TriggerTypeSessionStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One time.
        /// </summary>
        internal static string TriggerTypeTime {
            get {
                return ResourceManager.GetString("TriggerTypeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekly.
        /// </summary>
        internal static string TriggerTypeWeekly {
            get {
                return ResourceManager.GetString("TriggerTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} every {1} of every week, starting {0:d}.
        /// </summary>
        internal static string TriggerWeekly1Week {
            get {
                return ResourceManager.GetString("TriggerWeekly1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At {0:t} every {1} of every {2} weeks, starting {0:d}.
        /// </summary>
        internal static string TriggerWeeklyMultWeeks {
            get {
                return ResourceManager.GetString("TriggerWeeklyMultWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à every.
        /// </summary>
        internal static string WWAllWeeks {
            get {
                return ResourceManager.GetString("WWAllWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fifth.
        /// </summary>
        internal static string WWFifthWeek {
            get {
                return ResourceManager.GetString("WWFifthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à first.
        /// </summary>
        internal static string WWFirstWeek {
            get {
                return ResourceManager.GetString("WWFirstWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fourth.
        /// </summary>
        internal static string WWFourthWeek {
            get {
                return ResourceManager.GetString("WWFourthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à last.
        /// </summary>
        internal static string WWLastWeek {
            get {
                return ResourceManager.GetString("WWLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à second.
        /// </summary>
        internal static string WWSecondWeek {
            get {
                return ResourceManager.GetString("WWSecondWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à third.
        /// </summary>
        internal static string WWThirdWeek {
            get {
                return ResourceManager.GetString("WWThirdWeek", resourceCulture);
            }
        }
    }
}
